version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "${DB_PORT:-3307}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: '${DB_DATABASE:-business_management_db}'
      MYSQL_USER: '${DB_USERNAME:-business_management_user}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-business_management_secret}'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
