services:
  app:
    build:
      context: .
      dockerfile: ./docker/DockerFile
    image: laravel-app
    container_name: business_management_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
      - "5173:5173"
    depends_on:
      - mysql
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSE_BAKE=true
    networks:
      - business-management-network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - business-management-network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "${DB_PORT:-3310}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: '${DB_DATABASE:-business_management_db}'
      MYSQL_USER: '${DB_USERNAME:-business_management_user}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-business_management_secret}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - business-management-network

networks:
  business-management-network:
    driver: bridge

volumes:
  mysql_data:
