FROM php:8.2-fpm

ARG APP_DIR=/var/www

RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libjpeg-dev \
    libfreetype6-dev \
    npm \
    nodejs

RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

WORKDIR ${APP_DIR}

COPY --chown=www-data:www-data ../ .

RUN if [ -f .env.example ]; then cp .env.example .env; fi

RUN rm -f composer.lock package-lock.json
RUN composer install --no-interaction --prefer-dist --optimize-autoloader
RUN npm install

RUN chown -R www-data:www-data ${APP_DIR}/storage ${APP_DIR}/bootstrap/cache

RUN php artisan key:generate

RUN npm run build

EXPOSE 9000

CMD ["php-fpm"]
