FROM php:8.2-fpm

# define diretorio de trabalho
ARG APP_DIR=/var/www

# Instala extensões e dependências do sistema
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libjpeg-dev \
    libfreetype6-dev \
    npm \
    nodejs

# Instala extensões PHP necessárias para Laravel
RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd zip

# Instala Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Instala Node.js (versão LTS)
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

# Define diretório de trabalho
WORKDIR ${APP_DIR}

# Copia arquivos do projeto
COPY --chown=www-data:www-data ../ .

# Instala dependências PHP e JS
RUN rm -f composer.lock package-lock.json
RUN composer install --no-interaction --prefer-dist --optimize-autoloader
RUN npm install

# Permissões para o storage e cache
RUN chown -R www-data:www-data ${APP_DIR}/storage ${APP_DIR}/bootstrap/cache

EXPOSE 9000

CMD ["php-fpm"]
